# Generated by Django 6.0.6 on 2026-06-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('traceback', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UNRESOLVED', 'Unresolved'), ('RESOLVED', 'Resolved')], default='UNRESOLVED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
