# Generated by Django 6.0.6 on 2026-06-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fitid',
            field=models.CharField(blank=True, help_text='OFX Transaction ID to prevent duplicates', max_length=255, null=True),
        ),
    ]
