# Generated by Django 6.0.6 on 2026-06-10 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0003_bankaccount_current_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('base_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gateway_fee_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('desired_margin_percent', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('simples_nacional_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
        ),
    ]
