# Generated by Django 6.0.6 on 2026-06-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_productpricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
