# Generated by Django 6.0.6 on 2026-06-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_bankaccount_deleted_at_bankaccount_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricing',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productpricing',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
