# Generated by Django 6.0.6 on 2026-06-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CNAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('is_subject_to_fator_r', models.BooleanField(default=False)),
                ('default_anexo', models.CharField(choices=[('I', 'Anexo I - Comércio'), ('II', 'Anexo II - Indústria'), ('III', 'Anexo III - Serviços'), ('IV', 'Anexo IV - Serviços'), ('V', 'Anexo V - Serviços')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimplesNacionalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('anexo', models.CharField(choices=[('I', 'Anexo I'), ('II', 'Anexo II'), ('III', 'Anexo III'), ('IV', 'Anexo IV'), ('V', 'Anexo V')], max_length=5)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
