# Generated by Django 6.0.6 on 2026-06-10 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.company'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='primary_cnae',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_companies', to='companies.cnae'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='secondary_cnaes',
            field=models.ManyToManyField(blank=True, related_name='secondary_companies', to='companies.cnae'),
        ),
        migrations.AddField(
            model_name='simplesnacionalhistory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simples_nacional_history', to='core.company'),
        ),
    ]
