# Generated by Django 6.0.6 on 2026-06-10 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyHealthMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('cash_flow_volatility', models.FloatField(default=0.0, help_text='Variance in monthly net profit')),
                ('working_capital_ratio', models.FloatField(default=0.0, help_text='Cash reserves / Average monthly expenses')),
                ('account_mixing_score', models.FloatField(default=0.0, help_text='Percentage of transactions marked as Personal/PF')),
                ('reactive_monitoring_score', models.FloatField(default=0.0, help_text='Calculated based on login frequency vs transaction volume')),
                ('bankruptcy_risk_score', models.FloatField(blank=True, help_text='0-100 probability of bankruptcy in 12 months', null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to='core.company')),
            ],
        ),
    ]
