# Generated by Django 6.0.6 on 2026-06-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyhealthmetrics',
            name='runway_months',
            field=models.FloatField(blank=True, help_text='Months left before cash runs out', null=True),
        ),
        migrations.AddField(
            model_name='companyhealthmetrics',
            name='tax_optimization_alert',
            field=models.TextField(blank=True, help_text='Alert if Lucro Presumido is cheaper', null=True),
        ),
    ]
