# Generated by Django 6.0.6 on 2026-06-16 23:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_companyhealthmetrics_runway_months_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymizedDataSnapshot',
            fields=[
                ('snapshot_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cnae_sector', models.CharField(blank=True, max_length=100, null=True)),
                ('b2b_vs_b2c_ratio', models.FloatField(default=0.0, help_text='% of B2B transactions')),
                ('simples_nacional_burden', models.FloatField(default=0.0, help_text='% of revenue spent on DAS')),
                ('payroll_ratio', models.FloatField(default=0.0, help_text='Fator R payroll-to-revenue ratio')),
                ('account_mixing_score', models.FloatField(default=0.0)),
                ('cash_flow_volatility', models.FloatField(default=0.0)),
                ('fixed_vs_variable_costs', models.FloatField(default=0.0, help_text='% of expenses that are fixed')),
                ('working_capital_ratio', models.FloatField(default=0.0)),
                ('debt_payment_ratio', models.FloatField(default=0.0, help_text='% of expenses going to debt/loans')),
                ('runway_months', models.FloatField(default=999.0)),
                ('is_insolvent', models.BooleanField(default=False, help_text='Did the company go bankrupt / fail?')),
            ],
        ),
    ]
