# Generated by Django 6.0.6 on 2026-06-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DASCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(help_text='1-12')),
                ('year', models.IntegerField()),
                ('rbt12', models.DecimalField(decimal_places=2, help_text='Receita Bruta 12 Meses', max_digits=12)),
                ('revenue_month', models.DecimalField(decimal_places=2, max_digits=12)),
                ('anexo_applied', models.CharField(max_length=5)),
                ('fator_r', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('aliquota_efetiva', models.DecimalField(decimal_places=6, max_digits=7)),
                ('das_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RevenueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(help_text='1-12')),
                ('year', models.IntegerField(help_text='e.g. 2026')),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0.0, help_text='Faturamento Bruto', max_digits=12)),
                ('payroll_expense', models.DecimalField(decimal_places=2, default=0.0, help_text='Folha de Pagamentos (for Fator r)', max_digits=12)),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='TaxBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anexo', models.CharField(max_length=5)),
                ('faixa', models.IntegerField(help_text='1 to 6')),
                ('min_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('aliquota_nominal', models.DecimalField(decimal_places=4, help_text='e.g. 0.0400 for 4%', max_digits=5)),
                ('parcela_deduzir', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ['anexo', 'faixa'],
            },
        ),
    ]
