# Generated by Django 6.0.6 on 2026-06-10 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dascalculation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='das_calculations', to='core.company'),
        ),
        migrations.AddField(
            model_name='revenuerecord',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_records', to='core.company'),
        ),
        migrations.AlterUniqueTogether(
            name='taxbracket',
            unique_together={('anexo', 'faixa')},
        ),
        migrations.AlterUniqueTogether(
            name='dascalculation',
            unique_together={('company', 'month', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='revenuerecord',
            unique_together={('company', 'month', 'year')},
        ),
    ]
